import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    borderRadius: {
      none: "0px",
      "extra-small": "2px",
      small: "8px",
      medium: "12px",
      large: "16px",
      "extra-large": "28px",
      full: "9999px",
    },
    colors: {
      transparent: "transparent",
      primary: {
        DEFAULT: "rgb(var(--primary))",
        container: "rgb(var(--primary-container))",
        fixed: {
          DEFAULT: "rgb(var(--primary-fixed))",
          opacity: {
            0: "rgba(var(--primary-fixed-opacity-0))",
            8: "rgba(var(--primary-fixed-opacity-8))",
            12: "rgba(var(--primary-fixed-opacity-12))",
            16: "rgba(var(--primary-fixed-opacity-16))",
            50: "rgba(var(--primary-fixed-opacity-50))",
          },
        },
        "fixed-dim": {
          DEFAULT: "rgb(var(--primary-fixed-dim))",
          opacity: {
            0: "rgba(var(--primary-fixed-dim-opacity-0))",
            8: "rgba(var(--primary-fixed-dim-opacity-8))",
            12: "rgba(var(--primary-fixed-dim-opacity-12))",
            16: "rgba(var(--primary-fixed-dim-opacity-16))",
            50: "rgba(var(--primary-fixed-dim-opacity-50))",
          },
        },
        0: "rgb(var(--primary-0))",
        5: "rgb(var(--primary-5))",
        10: "rgb(var(--primary-10))",
        15: "rgb(var(--primary-15))",
        20: "rgb(var(--primary-20))",
        25: "rgb(var(--primary-25))",
        30: "rgb(var(--primary-30))",
        35: "rgb(var(--primary-35))",
        40: "rgb(var(--primary-40))",
        50: "rgb(var(--primary-50))",
        60: "rgb(var(--primary-60))",
        70: "rgb(var(--primary-70))",
        80: "rgb(var(--primary-80))",
        90: "rgb(var(--primary-90))",
        95: "rgb(var(--primary-95))",
        98: "rgb(var(--primary-98))",
        99: "rgb(var(--primary-99))",
        100: "rgb(var(--primary-100))",
        opacity: {
          0: "rgba(var(--primary-opacity-0))",
          8: "rgba(var(--primary-opacity-8))",
          12: "rgba(var(--primary-opacity-12))",
          16: "rgba(var(--primary-opacity-16))",
          50: "rgba(var(--primary-opacity-50))",
        },
      },
      secondary: {
        DEFAULT: "rgb(var(--secondary))",
        container: {
          DEFAULT: "rgb(var(--secondary-container))",
          opacity: {
            0: "rgba(var(--secondary-container-opacity-0))",
            8: "rgba(var(--secondary-container-opacity-8))",
            12: "rgba(var(--secondary-container-opacity-12))",
            16: "rgba(var(--secondary-container-opacity-16))",
            50: "rgba(var(--secondary-container-opacity-50))",
          },
        },
        fixed: {
          DEFAULT: "rgb(var(--secondary-fixed))",
          opacity: {
            0: "rgba(var(--secondary-fixed-opacity-0))",
            8: "rgba(var(--secondary-fixed-opacity-8))",
            12: "rgba(var(--secondary-fixed-opacity-12))",
            16: "rgba(var(--secondary-fixed-opacity-16))",
            50: "rgba(var(--secondary-fixed-opacity-50))",
          },
          dim: {
            opacity: {
              0: "rgba(var(--secondary-fixed-dim-opacity-0))",
              8: "rgba(var(--secondary-fixed-dim-opacity-8))",
              12: "rgba(var(--secondary-fixed-dim-opacity-12))",
              16: "rgba(var(--secondary-fixed-dim-opacity-16))",
              50: "rgba(var(--secondary-fixed-dim-opacity-50))",
            },
          },
        },
        "fixed-dim": "rgb(var(--secondary-fixed-dim))",
        0: "rgb(var(--secondary-0))",
        10: "rgb(var(--secondary-10))",
        15: "rgb(var(--secondary-15))",
        20: "rgb(var(--secondary-20))",
        25: "rgb(var(--secondary-25))",
        30: "rgb(var(--secondary-30))",
        35: "rgb(var(--secondary-35))",
        40: "rgb(var(--secondary-40))",
        50: "rgb(var(--secondary-50))",
        60: "rgb(var(--secondary-60))",
        70: "rgb(var(--secondary-70))",
        80: "rgb(var(--secondary-80))",
        90: "rgb(var(--secondary-90))",
        95: "rgb(var(--secondary-95))",
        98: "rgb(var(--secondary-98))",
        99: "rgb(var(--secondary-99))",
        100: "rgb(var(--secondary-100))",
        opacity: {
          0: "rgb(var(--secondary-opacity-0))",
          8: "rgb(var(--secondary-opacity-8))",
          12: "rgb(var(--secondary-opacity-12))",
          16: "rgb(var(--secondary-opacity-16))",
          50: "rgb(var(--secondary-opacity-50))",
        },
      },
      error: {
        DEFAULT: "rgb(var(--error))",
        container: {
          DEFAULT: "rgb(var(--error-container))",
          opacity: {
            0: "rgba(var(--error-container-opacity-0))",
            8: "rgba(var(--error-container-opacity-8))",
            12: "rgba(var(--error-container-opacity-12))",
            16: "rgba(var(--error-container-opacity-16))",
            50: "rgba(var(--error-container-opacity-50))",
          },
        },
        0: "rgb(var(--error-0))",
        10: "rgb(var(--error-10))",
        15: "rgb(var(--error-15))",
        20: "rgb(var(--error-20))",
        25: "rgb(var(--error-25))",
        30: "rgb(var(--error-30))",
        35: "rgb(var(--error-35))",
        40: "rgb(var(--error-40))",
        50: "rgb(var(--error-50))",
        60: "rgb(var(--error-60))",
        70: "rgb(var(--error-70))",
        80: "rgb(var(--error-80))",
        90: "rgb(var(--error-90))",
        95: "rgb(var(--error-95))",
        98: "rgb(var(--error-98))",
        99: "rgb(var(--error-99))",
        100: "rgb(var(--error-100))",
        opacity: {
          0: "rgba(var(--error-opacity-0))",
          8: "rgba(var(--error-opacity-8))",
          12: "rgba(var(--error-opacity-12))",
          16: "rgba(var(--error-opacity-16))",
          50: "rgba(var(--error-opacity-50))",
        },
      },
      warning: {
        DEFAULT: "rgb(var(--warning))",
        container: "rgb(var(--warning-container))",
        0: "rgb(var(--warning-0))",
        10: "rgb(var(--warning-10))",
        15: "rgb(var(--warning-15))",
        20: "rgb(var(--warning-20))",
        25: "rgb(var(--warning-25))",
        30: "rgb(var(--warning-30))",
        35: "rgb(var(--warning-35))",
        40: "rgb(var(--warning-40))",
        50: "rgb(var(--warning-50))",
        60: "rgb(var(--warning-60))",
        70: "rgb(var(--warning-70))",
        80: "rgb(var(--warning-80))",
        90: "rgb(var(--warning-90))",
        95: "rgb(var(--warning-95))",
        98: "rgb(var(--warning-98))",
        99: "rgb(var(--warning-99))",
        100: "rgb(var(--warning-100))",
        opacity: {
          0: "rgba(var(--warning-opacity-0))",
          8: "rgba(var(--warning-opacity-8))",
          12: "rgba(var(--warning-opacity-12))",
          16: "rgba(var(--warning-opacity-16))",
          50: "rgba(var(--warning-opacity-50))",
        },
      },
      positive: {
        DEFAULT: "rgb(var(--positive))",
        container: "rgb(var(--positive-container))",
        0: "rgb(var(--positive-0))",
        10: "rgb(var(--positive-10))",
        15: "rgb(var(--positive-15))",
        20: "rgb(var(--positive-20))",
        25: "rgb(var(--positive-25))",
        30: "rgb(var(--positive-30))",
        35: "rgb(var(--positive-35))",
        40: "rgb(var(--positive-40))",
        50: "rgb(var(--positive-50))",
        60: "rgb(var(--positive-60))",
        70: "rgb(var(--positive-70))",
        80: "rgb(var(--positive-80))",
        90: "rgb(var(--positive-90))",
        95: "rgb(var(--positive-95))",
        98: "rgb(var(--positive-98))",
        99: "rgb(var(--positive-99))",
        100: "rgb(var(--positive-100))",
        opacity: {
          0: "rgba(var(--positive-opacity-0))",
          8: "rgba(var(--positive-opacity-8))",
          12: "rgba(var(--positive-opacity-12))",
          16: "rgba(var(--positive-opacity-16))",
          50: "rgba(var(--positive-opacity-50))",
        },
      },
      informative: {
        DEFAULT: "rgb(var(--informative))",
        container: "rgb(var(--informative-container))",
        0: "rgb(var(--informative-0))",
        10: "rgb(var(--informative-10))",
        15: "rgb(var(--informative-15))",
        20: "rgb(var(--informative-20))",
        25: "rgb(var(--informative-25))",
        30: "rgb(var(--informative-30))",
        35: "rgb(var(--informative-35))",
        40: "rgb(var(--informative-40))",
        50: "rgb(var(--informative-50))",
        60: "rgb(var(--informative-60))",
        70: "rgb(var(--informative-70))",
        80: "rgb(var(--informative-80))",
        90: "rgb(var(--informative-90))",
        95: "rgb(var(--informative-95))",
        98: "rgb(var(--informative-98))",
        99: "rgb(var(--informative-99))",
        100: "rgb(var(--informative-100))",
        opacity: {
          0: "rgba(var(--informative-opacity-0))",
          8: "rgba(var(--informative-opacity-8))",
          12: "rgba(var(--informative-opacity-12))",
          16: "rgba(var(--informative-opacity-16))",
          50: "rgba(var(--informative-opacity-50))",
        },
      },
      neutral: {
        0: "rgb(var(--neutral-0))",
        5: "rgb(var(--neutral-5))",
        10: "rgb(var(--neutral-10))",
        15: "rgb(var(--neutral-15))",
        20: "rgb(var(--neutral-20))",
        25: "rgb(var(--neutral-25))",
        30: "rgb(var(--neutral-30))",
        35: "rgb(var(--neutral-35))",
        40: "rgb(var(--neutral-40))",
        50: "rgb(var(--neutral-50))",
        60: "rgb(var(--neutral-60))",
        70: "rgb(var(--neutral-70))",
        80: "rgb(var(--neutral-80))",
        87: "rgb(var(--neutral-87))",
        90: "rgb(var(--neutral-90))",
        92: "rgb(var(--neutral-92))",
        94: "rgb(var(--neutral-94))",
        95: "rgb(var(--neutral-95))",
        96: "rgb(var(--neutral-96))",
        98: "rgb(var(--neutral-98))",
        99: "rgb(var(--neutral-99))",
        100: "rgb(var(--neutral-100))",
      },
      "neutral-variant": {
        0: "rgb(var(--neutral-variant-0))",
        5: "rgb(var(--neutral-variant-5))",
        10: "rgb(var(--neutral-variant-10))",
        15: "rgb(var(--neutral-variant-15))",
        20: "rgb(var(--neutral-variant-20))",
        25: "rgb(var(--neutral-variant-25))",
        30: "rgb(var(--neutral-variant-30))",
        35: "rgb(var(--neutral-variant-35))",
        40: "rgb(var(--neutral-variant-40))",
        50: "rgb(var(--neutral-variant-50))",
        60: "rgb(var(--neutral-variant-60))",
        70: "rgb(var(--neutral-variant-70))",
        80: "rgb(var(--neutral-variant-80))",
        90: "rgb(var(--neutral-variant-90))",
        95: "rgb(var(--neutral-variant-95))",
        98: "rgb(var(--neutral-variant-98))",
        99: "rgb(var(--neutral-variant-99))",
        100: "rgb(var(--neutral-variant-100))",
      },
      surface: {
        DEFAULT: "rgb(var(--surface))",
        dim: {
          DEFAULT: "rgb(var(--surface-dim))",
          opacity: {
            0: "rgba(var(--surface-dim-opacity-0))",
            8: "rgba(var(--surface-dim-opacity-8))",
            12: "rgba(var(--surface-dim-opacity-12))",
            16: "rgba(var(--surface-dim-opacity-16))",
            50: "rgba(var(--surface-dim-opacity-50))",
          },
        },
        variant: {
          DEFAULT: "rgb(var(--surface-variant))",
          opacity: {
            0: "rgba(var(--surface-variant-opacity-0))",
            8: "rgba(var(--surface-variant-opacity-8))",
            12: "rgba(var(--surface-variant-opacity-12))",
            16: "rgba(var(--surface-variant-opacity-16))",
            50: "rgba(var(--surface-variant-opacity-50))",
          },
        },
        bright: {
          DEFAULT: "rgb(var(--surface-bright))",
          opacity: {
            0: "rgba(var(--surface-bright-opacity-0))",
            8: "rgba(var(--surface-bright-opacity-8))",
            12: "rgba(var(--surface-bright-opacity-12))",
            16: "rgba(var(--surface-bright-opacity-16))",
            50: "rgba(var(--surface-bright-opacity-50))",
          },
        },
        tint: {
          DEFAULT: "rgb(var(--surface-tint))",
          opacity: {
            0: "rgba(var(--surface-tint-opacity-0))",
            8: "rgba(var(--surface-tint-opacity-8))",
            12: "rgba(var(--surface-tint-opacity-12))",
            16: "rgba(var(--surface-tint-opacity-16))",
            50: "rgba(var(--surface-tint-opacity-50))",
          },
        },
        container: {
          DEFAULT: "rgb(var(--surface-container))",
          opacity: {
            0: "rgba(var(--surface-container-opacity-0))",
            8: "rgba(var(--surface-container-opacity-8))",
            12: "rgba(var(--surface-container-opacity-12))",
            16: "rgba(var(--surface-container-opacity-16))",
            50: "rgba(var(--surface-container-opacity-50))",
          },
        },
        "container-low": {
          DEFAULT: "rgb(var(--surface-container-low))",
          opacity: {
            0: "rgba(var(--surface-container-low-opacity-0))",
            8: "rgba(var(--surface-container-low-opacity-8))",
            12: "rgba(var(--surface-container-low-opacity-12))",
            16: "rgba(var(--surface-container-low-opacity-16))",
            50: "rgba(var(--surface-container-low-opacity-50))",
          },
        },
        "container-lowest": {
          DEFAULT: "rgb(var(--surface-container-lowest))",
          opacity: {
            0: "rgba(var(--surface-container-lowest-opacity-0))",
            8: "rgba(var(--surface-container-lowest-opacity-8))",
            12: "rgba(var(--surface-container-lowest-opacity-12))",
            16: "rgba(var(--surface-container-lowest-opacity-16))",
            50: "rgba(var(--surface-container-lowest-opacity-50))",
          },
        },
        "container-high": {
          DEFAULT: "rgb(var(--surface-container-high))",
          opacity: {
            0: "rgba(var(--surface-container-high-opacity-0))",
            8: "rgba(var(--surface-container-high-opacity-8))",
            12: "rgba(var(--surface-container-high-opacity-12))",
            16: "rgba(var(--surface-container-high-opacity-16))",
            50: "rgba(var(--surface-container-high-opacity-50))",
          },
        },
        "container-highest": {
          DEFAULT: "rgb(var(--surface-container-highest))",
          opacity: {
            0: "rgba(var(--surface-container-highest-opacity-0))",
            8: "rgba(var(--surface-container-highest-opacity-8))",
            12: "rgba(var(--surface-container-highest-opacity-12))",
            16: "rgba(var(--surface-container-highest-opacity-16))",
            50: "rgba(var(--surface-container-highest-opacity-50))",
          },
        },
        opacity: {
          0: "rgba(var(--surface-opacity-0))",
          8: "rgba(var(--surface-opacity-8))",
          12: "rgba(var(--surface-opacity-12))",
          16: "rgba(var(--surface-opacity-16))",
          50: "rgba(var(--surface-opacity-50))",
        },
      },
      on: {
        primary: {
          DEFAULT: "rgb(var(--on-primary))",
          container: {
            DEFAULT: "rgb(var(--on-primary-container))",
            opacity: {
              0: "rgba(var(--on-primary-container-opacity-0))",
              8: "rgba(var(--on-primary-container-opacity-8))",
              12: "rgba(var(--on-primary-container-opacity-12))",
              16: "rgba(var(--on-primary-container-opacity-16))",
              50: "rgba(var(--on-primary-container-opacity-50))",
            },
          },
          fixed: {
            opacity: {
              0: "rgba(var(--on-primary-fixed-opacity-0))",
              8: "rgba(var(--on-primary-fixed-opacity-8))",
              12: "rgba(var(--on-primary-fixed-opacity-12))",
              16: "rgba(var(--on-primary-fixed-opacity-16))",
              50: "rgba(var(--on-primary-fixed-opacity-50))",
            },
            variant: {
              opacity: {
                0: "rgba(var(--on-primary-fixed-variant-opacity-0))",
                8: "rgba(var(--on-primary-fixed-variant-opacity-8))",
                12: "rgba(var(--on-primary-fixed-variant-opacity-12))",
                16: "rgba(var(--on-primary-fixed-variant-opacity-16))",
                50: "rgba(var(--on-primary-fixed-variant-opacity-50))",
              },
            },
          },
          opacity: {
            0: "rgba(var(--on-primary-opacity-0))",
            8: "rgba(var(--on-primary-opacity-8))",
            12: "rgba(var(--on-primary-opacity-12))",
            16: "rgba(var(--on-primary-opacity-16))",
            50: "rgba(var(--on-primary-opacity-50))",
          },
        },
        secondary: {
          DEFAULT: "rgb(var(--on-secondary))",
          container: {
            DEFAULT: "rgb(var(--on-secondary-container))",
            opacity: {
              0: "rgba(var(--on-secondary-container-opacity-0))",
              8: "rgba(var(--on-secondary-container-opacity-8))",
              12: "rgba(var(--on-secondary-container-opacity-12))",
              16: "rgba(var(--on-secondary-container-opacity-16))",
              50: "rgba(var(--on-secondary-container-opacity-50))",
            },
          },
          fixed: {
            opacity: {
              0: "rgba(var(--on-secondary-fixed-opacity-0))",
              8: "rgba(var(--on-secondary-fixed-opacity-8))",
              12: "rgba(var(--on-secondary-fixed-opacity-12))",
              16: "rgba(var(--on-secondary-fixed-opacity-16))",
              50: "rgba(var(--on-secondary-fixed-opacity-50))",
            },
            variant: {
              opacity: {
                0: "rgba(var(--on-secondary-fixed-variant-opacity-0))",
                8: "rgba(var(--on-secondary-fixed-variant-opacity-8))",
                12: "rgba(var(--on-secondary-fixed-variant-opacity-12))",
                16: "rgba(var(--on-secondary-fixed-variant-opacity-16))",
                50: "rgba(var(--on-secondary-fixed-variant-opacity-50))",
              },
            },
          },
          opacity: {
            0: "rgba(var(--on-secondary-opacity-0))",
            8: "rgba(var(--on-secondary-opacity-8))",
            12: "rgba(var(--on-secondary-opacity-12))",
            16: "rgba(var(--on-secondary-opacity-16))",
            50: "rgba(var(--on-secondary-opacity-50))",
          },
        },
        error: {
          DEFAULT: "rgb(var(--on-error))",
          container: {
            DEFAULT: "rgb(var(--on-error-container))",
            opacity: {
              0: "rgba(var(--on-error-container-opacity-0))",
              8: "rgba(var(--on-error-container-opacity-8))",
              12: "rgba(var(--on-error-container-opacity-12))",
              16: "rgba(var(--on-error-container-opacity-16))",
              50: "rgba(var(--on-error-container-opacity-50))",
            },
          },
          opacity: {
            0: "rgba(var(--on-error-opacity-0))",
            8: "rgba(var(--on-error-opacity-8))",
            12: "rgba(var(--on-error-opacity-12))",
            16: "rgba(var(--on-error-opacity-16))",
            50: "rgba(var(--on-error-opacity-50))",
          },
        },
        positive: {
          DEFAULT: "rgb(var(--on-positive))",
          container: "rgb(var(--on-positive-container))",
        },
        warning: {
          DEFAULT: "rgb(var(--on-warning))",
          container: "rgb(var(--on-warning-container))",
        },
        informative: {
          DEFAULT: "rgb(var(--on-informative))",
          container: "rgb(var(--on-informative-container))",
        },
        surface: {
          DEFAULT: "rgb(var(--on-surface))",
          variant: {
            DEFAULT: "rgb(var(--on-surface-variant))",
            opacity: {
              0: "rgba(var(--on-surface-variant-opacity-0))",
              8: "rgba(var(--on-surface-variant-opacity-8))",
              12: "rgba(var(--on-surface-variant-opacity-12))",
              16: "rgba(var(--on-surface-variant-opacity-16))",
              50: "rgba(var(--on-surface-variant-opacity-50))",
            },
          },
          opacity: {
            0: "rgba(var(--on-surface-opacity-0))",
            8: "rgba(var(--on-surface-opacity-8))",
            12: "rgba(var(--on-surface-opacity-12))",
            16: "rgba(var(--on-surface-opacity-16))",
            50: "rgba(var(--on-surface-opacity-50))",
          },
        },
        "primary-fixed": {
          DEFAULT: "rgb(var(--on-primary-fixed))",
          variant: "rgb(var(--on-primary-fixed-variant))",
        },
        "secondary-fixed": {
          DEFAULT: "rgb(var(--on-secondary-fixed))",
          variant: "rgb(var(--on-secondary-fixed-variant))",
        },
        background: {
          DEFAULT: "rgb(var(--on-background))",
          opacity: {
            0: "rgba(var(--on-background-opacity-0))",
            8: "rgba(var(--on-background-opacity-8))",
            12: "rgba(var(--on-background-opacity-12))",
            16: "rgba(var(--on-background-opacity-16))",
            50: "rgba(var(--on-background-opacity-50))",
          },
        },
      },
      inverse: {
        surface: {
          DEFAULT: "rgb(var(--inverse-surface))",
          opacity: {
            0: "rgba(var(--inverse-surface-opacity-0))",
            8: "rgba(var(--inverse-surface-opacity-8))",
            12: "rgba(var(--inverse-surface-opacity-12))",
            16: "rgba(var(--inverse-surface-opacity-16))",
            50: "rgba(var(--inverse-surface-opacity-50))",
          },
        },
        "on-surface": {
          DEFAULT: "rgb(var(--inverse-on-surface))",
          opacity: {
            0: "rgba(var(--inverse-on-surface-opacity-0))",
            8: "rgba(var(--inverse-on-surface-opacity-8))",
            12: "rgba(var(--inverse-on-surface-opacity-12))",
            16: "rgba(var(--inverse-on-surface-opacity-16))",
            50: "rgba(var(--inverse-on-surface-opacity-50))",
          },
        },
        primary: {
          DEFAULT: "rgb(var(--inverse-primary))",
          opacity: {
            0: "rgba(var(--inverse-primary-opacity-0))",
            8: "rgba(var(--inverse-primary-opacity-8))",
            12: "rgba(var(--inverse-primary-opacity-12))",
            16: "rgba(var(--inverse-primary-opacity-16))",
            50: "rgba(var(--inverse-primary-opacity-50))",
          },
        },
      },
      outline: {
        DEFAULT: "rgb(var(--outline))",
        variant: {
          DEFAULT: "rgb(var(--outline-variant))",
          opacity: {
            0: "rgba(var(--outline-variant-opacity-0))",
            8: "rgba(var(--outline-variant-opacity-8))",
            12: "rgba(var(--outline-variant-opacity-12))",
            16: "rgba(var(--outline-variant-opacity-16))",
            50: "rgba(var(--outline-variant-opacity-50))",
          },
        },
        opacity: {
          0: "rgba(var(--outline-opacity-0))",
          8: "rgba(var(--outline-opacity-8))",
          12: "rgba(var(--outline-opacity-12))",
          16: "rgba(var(--outline-opacity-16))",
          50: "rgba(var(--outline-opacity-50))",
        },
      },
      background: {
        DEFAULT: "rgb(var(--background))",
        opacity: {
          0: "rgba(var(--background-opacity-0))",
          8: "rgba(var(--background-opacity-8))",
          12: "rgba(var(--background-opacity-12))",
          16: "rgba(var(--background-opacity-16))",
          50: "rgba(var(--background-opacity-50))",
        },
      },
      scrim: {
        DEFAULT: "rgb(var(--scrim))",
        opacity: {
          0: "rgba(var(--scrim-opacity-0))",
          8: "rgba(var(--scrim-opacity-8))",
          12: "rgba(var(--scrim-opacity-12))",
          16: "rgba(var(--scrim-opacity-16))",
          50: "rgba(var(--scrim-opacity-50))",
        },
      },
      shadow: {
        DEFAULT: "rgb(var(--shadow))",
        opacity: {
          0: "rgba(var(--shadow-opacity-0))",
          8: "rgba(var(--shadow-opacity-8))",
          12: "rgba(var(--shadow-opacity-12))",
          16: "rgba(var(--shadow-opacity-16))",
          50: "rgba(var(--shadow-opacity-50))",
        },
      },
    },
    spacing: {
      0: "0px",
      2: "2px",
      4: "4px",
      6: "6px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
      64: "64px",
      80: "80px",
      96: "96px",
    },
    fontSize: {
      "display-large": [
        "57px",
        {
          lineHeight: "64px",
          fontWeight: "700",
        },
      ],
      "display-medium": [
        "45px",
        {
          lineHeight: "52px",
          fontWeight: "700",
        },
      ],
      "display-small": [
        "36px",
        {
          lineHeight: "44px",
          fontWeight: "700",
        },
      ],
      "headline-large": [
        "32px",
        {
          lineHeight: "40px",
          fontWeight: "400",
        },
      ],
      "headline-medium": [
        "28px",
        {
          lineHeight: "36px",
          fontWeight: "400",
        },
      ],
      "headline-small": [
        "24px",
        {
          lineHeight: "32px",
          fontWeight: "400",
        },
      ],
      "title-large": [
        "22px",
        {
          lineHeight: "28px",
          fontWeight: "700",
        },
      ],
      "title-medium": [
        "16px",
        {
          lineHeight: "24px",
          fontWeight: "700",
        },
      ],
      "title-small": [
        "14px",
        {
          lineHeight: "20px",
          fontWeight: "700",
        },
      ],
      "label-large": [
        "14px",
        {
          lineHeight: "20px",
          fontWeight: "500",
        },
      ],
      "label-large-prominent": [
        "14px",
        {
          lineHeight: "20px",
          fontWeight: "700",
        },
      ],
      "label-medium": [
        "12px",
        {
          lineHeight: "16px",
          fontWeight: "500",
        },
      ],
      "label-medium-prominent": [
        "12px",
        {
          lineHeight: "16px",
          fontWeight: "700",
        },
      ],
      "label-small": [
        "11px",
        {
          lineHeight: "16px",
          fontWeight: "500",
        },
      ],
      "body-large": [
        "16px",
        {
          lineHeight: "24px",
          fontWeight: "400",
        },
      ],
      "body-medium": [
        "14px",
        {
          lineHeight: "20px",
          fontWeight: "400",
        },
      ],
      "body-small": [
        "12px",
        {
          lineHeight: "16px",
          fontWeight: "400",
        },
      ],
    },
    extend: {
      animation: {
        "fade-slide": "fadeSlide 0.4s ease-out forwards",
        "fade-scale": "fadeScale 0.4s ease-out forwards",
      },
      keyframes: {
        fadeSlide: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeScale: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      fontFamily: {
        roboto: ["var(--font-roboto)"],
      },
      boxShadow: {
        "light-1": "0px 1px 10px 3px rgba(0, 0, 0, 0.10)",
        "light-2": "0px 2px 15px 3px rgba(0, 0, 0, 0.10)",
        "light-3": "0px 4px 20px 3px rgba(0, 0, 0, 0.10)",
        "light-4": "0px 6px 30px 3px rgba(0, 0, 0, 0.10)",
        "light-5": "0px 8px 50px 3px rgba(0, 0, 0, 0.10)",
      },
      textTransform: {
        "capitalize-first": "capitalize-first",
      },
      borderWidth: {
        "left-top": "1px 0 0px 1px",
        "right-top": "1px 1px 0px 0",
      },
      screens: {
        xs: "320px",
        sm: "375px",
      },
    },
  },
  plugins: [],
};
export default config;
