export enum PROFILE_STATUS {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  BLOCKED = "BLOCKED",
}

export enum ROLE {
  TRAVELER = "TRAVELER",
  CUSTOMER = "CUSTOMER",
}

export enum SERVICE_TYPE {
  VISIBLE_LOAD = "VISIBLE_LOAD",
  DOCUMENT = "DOCUMENT",
}

export enum TRIP_TYPE {
  SHIPPING = "SHIPPING",
  SHOPPING = "SHOPPING",
}

export enum ITEM_TYPE {
  DOCUMENT = "DOCUMENT",
  CLOTH = "CLOTH",
  FOOD = "FOOD",
  ELECTRONIC_GADGET = "ELECTRONIC_GADGET",
  OTHER = "OTHER",
}
