export const SEGMENTS = {
  "": "Home",
  "terms-of-service": "Terms & Conditions",
  "privacy-policy": "Privacy Policy",
  security: "Security",
  faq: "FAQ",
  "contact-us": "Contact Us",
  "about-us": "About us",
  "sign-in": "Sign in",
  "sign-in-with-email": "Sign in with Email",
  "sign-up": "Sign up",
  "sign-up-with-email": "Sign up with Email",
  "reset-password": "Reset Password",
  "successfull-email-sent": "Successfull Email Sent",
  "successfull-reset-password": "Successfull Reset Password",
  "set-new-password": "Set New Password",
  "confirm-new-password": "Confirm New Password",
  "ready-to-use": "Ready to Use",
  "legal-considerations": "Legal Considerations",
};
